DROP TABLE IF EXISTS cow CASCADE;
DROP TABLE IF EXISTS herd CASCADE;
DROP TABLE IF EXISTS breeder CASCADE;
DROP TABLE IF EXISTS operation CASCADE;
DROP TABLE IF EXISTS food CASCADE;
DROP TABLE IF EXISTS uses CASCADE;
